version: '3.3'

services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    image: martaswierczewska/backend
    restart: always
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      MYSQL_HOST: db
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

#  # Frontend Service
  app-client:
    image: martaswierczewska/frontend
    restart: always
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
    networks:
      - frontend

  # Database Service (Mysql)
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: documentsgraph
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
#      MYSQL_ROOT_PASSWORD: pass

    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
