insert into todos(description, category_category_id) values("Analiza prawna, w tym wskazanie zagrożeń",1);
insert into todos(description, category_category_id) values("Warunki zabudowy istniejące/wniosek",1);
insert into todos(description, category_category_id) values("Plan miejscowy",1);
insert into todos(description, category_category_id) values("Analiza przy współudziale projektanta (opcjonalnie)",1);
insert into todos(description, category_category_id) values("Badania geologiczne wstępne",1);
insert into todos(description, category_category_id) values("Badanie zanieczyszczeń gruntu",1);
insert into todos(description, category_category_id) values("Analiza kolizji z istniejącą infrastrukturą",1);
insert into todos(description, category_category_id) values("Wybór projektanta/konkurs",1);
insert into todos(description, category_category_id) values("Warunki techniczne media",2);
insert into todos(description, category_category_id) values("Energia elektryczna",2);
insert into todos(description, category_category_id) values("Gaz",2);
insert into todos(description, category_category_id) values("Woda i ścieki sanitarne",2);
insert into todos(description, category_category_id) values("Kanalizacja deszczowa",2);
insert into todos(description, category_category_id) values("Komunikacja, w tym zjazdy",2);
insert into todos(description, category_category_id) values("Przyłącze teletechniczne",2);
insert into todos(description, category_category_id) values("Pozwolenie środowiskowe",2);
insert into todos(description, category_category_id) values("Inwentaryzacja zieleni",2);
insert into todos(description, category_category_id) values("Badania geologiczne",2);
insert into todos(description, category_category_id) values("Kolizje sieciowe",2);
insert into todos(description, category_category_id) values("Ustalenie obszaru objętego projektem, w tym projekty podziału lub scalenia terenu",3);
insert into todos(description, category_category_id) values("Wytyczne dla projektanta do PB i PW",3);
insert into todos(description, category_category_id) values("Faza powstawania PB - współpraca z projektantem",3);
insert into todos(description, category_category_id) values("Zieleń-oczyszczenie terenu, projekt wycinki, ustalenie nasadzeń",3);
insert into todos(description, category_category_id) values("Odstępstwa branżowe (p.poż.,bud.,itp.)",3);
insert into todos(description, category_category_id) values("Wniosek o PnB",3);
insert into todos(description, category_category_id) values("Założenie rachunku deweloperskiego dla przedsięwzięcia mieszkaniowego",3);
insert into todos(description, category_category_id) values("PW - analiza prawidłowości wykonania, uzupełnienie przez projektanta",4);
insert into todos(description, category_category_id) values("PW - wytyczne do złożenia oferty dla GW",4);
insert into todos(description, category_category_id) values("Nabór ofert",4);
insert into todos(description, category_category_id) values("Wybór GW",4);
insert into todos(description, category_category_id) values("Założenie dziennika budowy",4);
insert into todos(description, category_category_id) values("Zgłoszenie budowy",4);
insert into todos(description, category_category_id) values("Umowa o roboty budowlane",4);
insert into todos(description, category_category_id) values("Ubezpieczenie budowy",4);
insert into todos(description, category_category_id) values("Nadzór inwestorski",5);
insert into todos(description, category_category_id) values("Koordynacja wytyczych warunków technicznych gestorów mediów",5);
insert into todos(description, category_category_id) values("Zgłaszanie etapów budowy do banku prowadzącego rachunek deweloperski",5);
insert into todos(description, category_category_id) values("Koordynacja wytycznych z umów przyłączeniowych",5);
insert into todos(description, category_category_id) values("Plan budżetu",6);
insert into todos(description, category_category_id) values("Przepływy finansowe",6);
insert into todos(description, category_category_id) values("Płatności do GW i podwykonawców",6);
insert into todos(description, category_category_id) values("Zabezpieczenia",6);
insert into todos(description, category_category_id) values("Koordynacja prac projektowych, oczekiwania klientów",7);
insert into todos(description, category_category_id) values("Badanie rynku",7);
insert into todos(description, category_category_id) values("Oferta sprzedażowa",7);
insert into todos(description, category_category_id) values("Targi mieszkaniowe",7);
insert into todos(description, category_category_id) values("Rozpoczęcie sprzedaży - termin",7);
insert into todos(description, category_category_id) values("Klient - koordynacja zmian projektowych (projektant-GW)",7);
insert into todos(description, category_category_id) values("Zgłoszenie zakończenia budowy",8);
insert into todos(description, category_category_id) values("PNU - wniosek, uzyskanie",8);
insert into todos(description, category_category_id) values("Odrębność lokali",8);
insert into todos(description, category_category_id) values("Dokumenty dla wspólnoty mieszkaniowej",8);
insert into todos(description, category_category_id) values("Przekazanie budynku zarządcy",8);
insert into todos(description, category_category_id) values("Informacje dotyczące zakupionego mieszkania",9);
insert into todos(description, category_category_id) values("Zgłaszane usterki",9);
insert into todos(description, category_category_id) values("Przedstawianie nowej oferty (pamiętać o RODO)",9);
insert into todos(description, category_category_id) values("Nowe oferty",9);
insert into todos(description, category_category_id) values("Kontakt z GW",10);
insert into todos(description, category_category_id) values("Koordynacja usuwania usterek - kontakt z klientem",10);
insert into todos(description, category_category_id) values("Tabela terminów gwarancyjnych",10);
insert into todos(description, category_category_id) values("Wykonania zastępcze",10);
insert into todos(description, category_category_id) values("Koszty usterek",10);
insert into todos(description, category_category_id) values("Wytyczne prawne",10);
insert into todos(description, category_category_id) values("Szkolenia",11);
insert into todos(description, category_category_id) values("Samochody",11);
insert into todos(description, category_category_id) values("Najbliższe wydarzenia",11);


insert into categories(name) values ("Przygotowanie inwestycji");
insert into categories(name) values ("Zakres administracyjny");
insert into categories(name) values ("Projektowanie");
insert into categories(name) values ("Przygotowanie budowy");
insert into categories(name) values ("Budowa");
insert into categories(name) values ("Finansowanie");
insert into categories(name) values ("Sprzedaż/marketing");
insert into categories(name) values ("Zakończenie budowy");
insert into categories(name) values ("Opieka posprzedażowa");
insert into categories(name) values ("Gwarancje i usuwanie usterek");
insert into categories(name) values ("Sprawy bieżące biura");


insert into houses(description, name_to_show, file_name_path) values ("Pierwsza inwestycja", "Toruń", "house1.jpg");
insert into houses(description, name_to_show, file_name_path) values ("Druga inwestycja", "Kraków", "house2.jpg");
insert into houses(description, name_to_show, file_name_path) values ("Trzecia inwestycja", "Warszawa", "house3.jpg");


insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 1);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 2);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 3);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 4);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 5);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 6);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 7);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 8);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 9);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 10);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 11);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 12);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 13);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 14);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 15);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 16);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 17);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 18);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 19);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 20);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 21);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 22);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 23);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 25);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 26);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 27);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 28);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 29);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 30);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 31);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 32);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 33);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 34);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 35);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 36);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 37);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 38);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 39);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 40);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 41);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 42);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 43);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 44);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 45);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 46);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 47);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 48);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 49);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 50);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 51);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 52);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 53);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 54);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 55);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 56);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 57);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 58);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 59);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 60);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 61);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 62);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 63);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 64);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 65);
insert into todo_connector(completed, document_id, house_house_id, todo_todo_id) values (false, 1, 1, 66);

insert into document(id, content, name) values(1, null, "");